
services:
  server:
    build: .
    container_name: server
    ## RUN GO application here
    command: go run server.go
    
  client:
    build: .
    ## RUN GO application here
    command: go run client.go
    deploy:
      replicas: 2
    depends_on:
      - server
